### ISSUE TITLE
Clarifying MeshBatcher Usage

### ISSUE THREAD

**Issue by MiqueiasDevGames** [OrigamiDev-Pete/MeshBatcher#6]
Could you give me a better explanation? what I understood was that when placing meshinstances as children of MeshBatcher at runtime they become a multimeshinstance which is good for performance, but I can't understand the inspector properties, how to use it:

Collision Ref
Scene Name
multimesh

Could you give me a more detailed explanation.

Thanks!!

**Comment by OrigamiDev-Pete** [comment]
Hi there,

Thanks for your interest in the plugin! The reason these inspector properties are visible is largely vestigial but can be useful to verify that the plugin is working correctly. All three fields should be automatically populated when batching and cleared when unbatching depending on if you use collisions and/or scenes as children of the MeshBatcher node.

The Collision Ref keeps a reference to a node that's created during batching that holds the staticBody and collisionShape nodes from the unbatched meshes.
![image](https://github.com/OrigamiDev-Pete/MeshBatcher/assets/55121683/5fe39889-773e-4c45-81f6-b2aabea9432f)

The Scene Name is only used if you are using a scene as a child of MeshBatcher so that it can regenerate the original scenes when unbatching.
![image](https://github.com/OrigamiDev-Pete/MeshBatcher/assets/55121683/267cef2a-73d8-4e33-8fcf-9665eb13abcf)

 And the Multimesh field is a product of using the MultiMesh node as a base node for the MeshBatcher node so we just inherit that one.

You're not required to use collisions or scenes when using MeshBatcher but if you do then node relationships need to be exactly as the pictures above, and everything should just work™.

I hope that helps!

**Comment by MiqueiasDevGames** [comment]
I got it, thanks!!
